# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Finds the k-th element in the sorted list efficiently
#'
#' This function finds the k-th element in the sorted list using the Quickselect algorithm.
#'
#' @param vec A numeric vector.
#' @param k The desired rank of the element (1-based index).
#'
#' @return The k-th element in the sorted list.
#'
#' @examples
#' vec <- c(3, 1, 4, 2, 5)
#' quickselect(vec, 3)
#'
#' @export
quickselect <- function(vec, k) {
    .Call(`_quantquickr_quickselect`, vec, k)
}

